package com.lynx.telemetry;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanContext;

/**
 * Reads the CURRENTLY ACTIVE OpenTelemetry span's trace/span id, if any.
 *
 * <p>This does NOT create spans, start tracing, or configure exporters — it only
 * reads whatever span a service's own instrumentation (typically Spring Boot's
 * {@code micrometer-tracing-bridge-otel}, wired per-service, not here) has
 * already made "current" on this thread. That's why the dependency is
 * {@code opentelemetry-api} only, not the SDK: reading context requires no
 * exporters, no samplers, no resource configuration — those belong to whatever
 * actually bootstraps tracing.
 *
 * <p>Distinct from {@code CorrelationId} (lynx-security): correlation-id is
 * Lynx's OWN application-level id, generated by our filter, propagated via an
 * HTTP header we control. Trace-id/span-id are OpenTelemetry's OWN identifiers,
 * generated by the tracing instrumentation itself, following the W3C Trace
 * Context standard. The two serve the same "reconstruct the request's path"
 * goal but come from different layers — both are commonly logged side by side.
 */
public final class TraceIds {

  /** The active trace id, or {@code ""} if no span is currently active. */
  public static String currentTraceId() {
    SpanContext context = Span.current().getSpanContext();
    return context.isValid() ? context.getTraceId() : "";
  }

  /** The active span id, or {@code ""} if no span is currently active. */
  public static String currentSpanId() {
    SpanContext context = Span.current().getSpanContext();
    return context.isValid() ? context.getSpanId() : "";
  }

  private TraceIds() {
  }
}
